import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class GlobalService {
  menu: String = ''
  items: Array<Object> = [
    {
      "id":7850,
      "description":"Brown Sugar & Peanut Mochi",
      "image":"https://source.unsplash.com/collection/1163637/480x480/?sig=55",
      "vendor_description":"芋頭風味粉",
      "cost":20.6,
      "packing_info":"0.6kg/bag 24bags/ctn",
      "uom":"bag",
      "base_uom":"kg",
      "max_order_qty":7,
      "primary_unit":0.6,
      "secondary_unit":24,
      "big_uom":"ctn",
      "cbm":4.6,
      "gw":7.2,
      "qty":19,
      "added_date":"2020-09-12",
      "status":true,
      "weight":46
    },
    {
      "id":9366,
      "description":"Mung Bean Cake",
      "image":"https://source.unsplash.com/collection/1163637/480x480/?sig=50",
      "vendor_description":"黑糖粉",
      "cost":20.6,
      "packing_info":"600ml/bottle 20bottles/ctn",
      "uom":"bottle",
      "base_uom":"ml",
      "max_order_qty":8,
      "primary_unit":600,
      "secondary_unit":20,
      "big_uom":"ctn",
      "cbm":1.4,
      "gw":1.2,
      "qty":55,
      "added_date":"2020-09-12",
      "status":true,
      "weight":95
    },
    {
      "id":8695,
      "description":"Q Mochi - Brown Sugar ",
      "image":"https://source.unsplash.com/collection/1163637/480x480/?sig=93",
      "vendor_description":"杏仁粉 ",
      "cost":120,
      "packing_info":"600ml/bottle 20bottles/ctn",
      "uom":"bottle",
      "base_uom":"ml",
      "max_order_qty":0,
      "primary_unit":600,
      "secondary_unit":20,
      "big_uom":"ctn",
      "cbm":9.2,
      "gw":0.5,
      "qty":12,
      "added_date":"2020-09-12",
      "status":true,
      "weight":2
    },
    {
      "id":8738,
      "description":"Q Mochi - Brown Sugar ",
      "image":"https://source.unsplash.com/collection/1163637/480x480/?sig=21",
      "vendor_description":"杏仁粉 ",
      "cost":120,
      "packing_info":"600ml/bottle 20bottles/ctn",
      "uom":"bottle",
      "base_uom":"ml",
      "max_order_qty":6,
      "primary_unit":600,
      "secondary_unit":20,
      "big_uom":"ctn",
      "cbm":3,
      "gw":5.8,
      "qty":99,
      "added_date":"2020-09-12",
      "status":false,
      "weight":82
    },
    {
      "id":5791,
      "description":"Sweet potato Taro balls",
      "image":"https://source.unsplash.com/collection/1163637/480x480/?sig=24",
      "vendor_description":"雞蛋仔專用粉-原味",
      "cost":30.5,
      "packing_info":"600ml/bottle 20bottles/ctn",
      "uom":"bottle",
      "base_uom":"ml",
      "max_order_qty":5,
      "primary_unit":600,
      "secondary_unit":20,
      "big_uom":"ctn",
      "cbm":7.7,
      "gw":4.8,
      "qty":54,
      "added_date":"2020-09-12",
      "status":true,
      "weight":91
    },
    {
      "id":5248,
      "description":"Taro",
      "image":"https://source.unsplash.com/collection/1163637/480x480/?sig=76",
      "vendor_description":"杏仁粉 ",
      "cost":30.5,
      "packing_info":"1kg/bag 6bags/ctn",
      "uom":"bag",
      "base_uom":"kg",
      "max_order_qty":9,
      "primary_unit":1,
      "secondary_unit":6,
      "big_uom":"ctn",
      "cbm":8.7,
      "gw":9.9,
      "qty":31,
      "added_date":"2020-09-12",
      "status":false,
      "weight":8
    },
    {
      "id":7528,
      "description":"Mini Taro balls",
      "image":"https://source.unsplash.com/collection/1163637/480x480/?sig=47",
      "vendor_description":"雞蛋仔專用粉-原味",
      "cost":120,
      "packing_info":"1kg/bag 6bags/ctn",
      "uom":"bag",
      "base_uom":"kg",
      "max_order_qty":5,
      "primary_unit":1,
      "secondary_unit":6,
      "big_uom":"ctn",
      "cbm":2.1,
      "gw":8.7,
      "qty":81,
      "added_date":"2020-09-12",
      "status":true,
      "weight":37
    },
    {
      "id":7857,
      "description":"Q Mochi - Original",
      "image":"https://source.unsplash.com/collection/1163637/480x480/?sig=97",
      "vendor_description":"黑糖粉",
      "cost":10.5,
      "packing_info":"600ml/bottle 20bottles/ctn",
      "uom":"bottle",
      "base_uom":"ml",
      "max_order_qty":7,
      "primary_unit":600,
      "secondary_unit":20,
      "big_uom":"ctn",
      "cbm":1.1,
      "gw":3.3,
      "qty":72,
      "added_date":"2020-09-12",
      "status":false,
      "weight":69
    },
    {
      "id":5916,
      "description":"Raw Soy Milk",
      "image":"https://source.unsplash.com/collection/1163637/480x480/?sig=32",
      "vendor_description":"焦糖粉",
      "cost":30.3,
      "packing_info":"1.2kg/bag 12bags/ctn",
      "uom":"bag",
      "base_uom":"kg",
      "max_order_qty":4,
      "primary_unit":1.2,
      "secondary_unit":12,
      "big_uom":"ctn",
      "cbm":1.3,
      "gw":5.8,
      "qty":49,
      "added_date":"2020-09-12",
      "status":false,
      "weight":85
    },
    {
      "id":4002,
      "description":"Barley",
      "image":"https://source.unsplash.com/collection/1163637/480x480/?sig=27",
      "vendor_description":"茉香綠茶",
      "cost":40.2,
      "packing_info":"12pcs/box 18boxes/ctn",
      "uom":"box",
      "base_uom":"pcs",
      "max_order_qty":4,
      "primary_unit":12,
      "secondary_unit":18,
      "big_uom":"ctn",
      "cbm":5.3,
      "gw":2.9,
      "qty":50,
      "added_date":"2020-09-12",
      "status":true,
      "weight":38
    },
    {
      "id":1139,
      "description":"Rice balls",
      "image":"https://source.unsplash.com/collection/1163637/480x480/?sig=46",
      "vendor_description":"杏仁粉 ",
      "cost":10.5,
      "packing_info":"12pcs/box 18boxes/ctn",
      "uom":"box",
      "base_uom":"pcs",
      "max_order_qty":3,
      "primary_unit":12,
      "secondary_unit":18,
      "big_uom":"ctn",
      "cbm":7.4,
      "gw":4.6,
      "qty":54,
      "added_date":"2020-09-12",
      "status":true,
      "weight":29
    },
    {
      "id":6351,
      "description":"Rice balls",
      "image":"https://source.unsplash.com/collection/1163637/480x480/?sig=51",
      "vendor_description":"鮮芋仙‐燒仙草粉",
      "cost":20.6,
      "packing_info":"1kg/bag 6bags/ctn",
      "uom":"bag",
      "base_uom":"kg",
      "max_order_qty":0,
      "primary_unit":1,
      "secondary_unit":6,
      "big_uom":"ctn",
      "cbm":2.2,
      "gw":8.2,
      "qty":87,
      "added_date":"2020-09-12",
      "status":true,
      "weight":78
    },
    {
      "id":3914,
      "description":"Brown Sugar & Peanut Mochi",
      "image":"https://source.unsplash.com/collection/1163637/480x480/?sig=77",
      "vendor_description":"奶精粉",
      "cost":40.2,
      "packing_info":"12pcs/box 18boxes/ctn",
      "uom":"box",
      "base_uom":"pcs",
      "max_order_qty":0,
      "primary_unit":12,
      "secondary_unit":18,
      "big_uom":"ctn",
      "cbm":10,
      "gw":8.4,
      "qty":80,
      "added_date":"2020-09-12",
      "status":true,
      "weight":65
    },
    {
      "id":8407,
      "description":"Jelly Noodle",
      "image":"https://source.unsplash.com/collection/1163637/480x480/?sig=13",
      "vendor_description":"茉香綠茶",
      "cost":40.2,
      "packing_info":"12pcs/box 18boxes/ctn",
      "uom":"box",
      "base_uom":"pcs",
      "max_order_qty":1,
      "primary_unit":12,
      "secondary_unit":18,
      "big_uom":"ctn",
      "cbm":0.2,
      "gw":1.3,
      "qty":68,
      "added_date":"2020-09-12",
      "status":false,
      "weight":47
    },
    {
      "id":7680,
      "description":"Barley",
      "image":"https://source.unsplash.com/collection/1163637/480x480/?sig=34",
      "vendor_description":"奶蓋粉",
      "cost":30.5,
      "packing_info":"1.2kg/bag 12bags/ctn",
      "uom":"bag",
      "base_uom":"kg",
      "max_order_qty":2,
      "primary_unit":1.2,
      "secondary_unit":12,
      "big_uom":"ctn",
      "cbm":6.9,
      "gw":1.2,
      "qty":64,
      "added_date":"2020-09-12",
      "status":true,
      "weight":50
    },
    {
      "id":6042,
      "description":"Mini Taro balls",
      "image":"https://source.unsplash.com/collection/1163637/480x480/?sig=97",
      "vendor_description":"雞蛋仔專用粉-原味",
      "cost":30.3,
      "packing_info":"12pcs/box 18boxes/ctn",
      "uom":"box",
      "base_uom":"pcs",
      "max_order_qty":6,
      "primary_unit":12,
      "secondary_unit":18,
      "big_uom":"ctn",
      "cbm":0.3,
      "gw":8.5,
      "qty":21,
      "added_date":"2020-09-12",
      "status":false,
      "weight":11
    },
    {
      "id":2994,
      "description":"Jelly Noodle",
      "image":"https://source.unsplash.com/collection/1163637/480x480/?sig=99",
      "vendor_description":"鮮芋仙‐燒仙草粉",
      "cost":130.7,
      "packing_info":"1.2kg/bag 12bags/ctn",
      "uom":"bag",
      "base_uom":"kg",
      "max_order_qty":1,
      "primary_unit":1.2,
      "secondary_unit":12,
      "big_uom":"ctn",
      "cbm":1.8,
      "gw":1.6,
      "qty":33,
      "added_date":"2020-09-12",
      "status":false,
      "weight":12
    },
    {
      "id":4554,
      "description":"Brown Sugar & Sesame Mochi",
      "image":"https://source.unsplash.com/collection/1163637/480x480/?sig=87",
      "vendor_description":"鮮芋仙紅茶",
      "cost":10.5,
      "packing_info":"0.6kg/bag 24bags/ctn",
      "uom":"bag",
      "base_uom":"kg",
      "max_order_qty":1,
      "primary_unit":0.6,
      "secondary_unit":24,
      "big_uom":"ctn",
      "cbm":5.4,
      "gw":5.9,
      "qty":89,
      "added_date":"2020-09-12",
      "status":true,
      "weight":18
    },
    {
      "id":7237,
      "description":"Q Mochi - Brown Sugar ",
      "image":"https://source.unsplash.com/collection/1163637/480x480/?sig=63",
      "vendor_description":"杏仁粉 ",
      "cost":130.7,
      "packing_info":"600ml/bottle 20bottles/ctn",
      "uom":"bottle",
      "base_uom":"ml",
      "max_order_qty":0,
      "primary_unit":600,
      "secondary_unit":20,
      "big_uom":"ctn",
      "cbm":7.4,
      "gw":2.2,
      "qty":25,
      "added_date":"2020-09-12",
      "status":false,
      "weight":51
    },
    {
      "id":1511,
      "description":"Raw Soy Milk",
      "image":"https://source.unsplash.com/collection/1163637/480x480/?sig=73",
      "vendor_description":"蜜香紅茶",
      "cost":20.6,
      "packing_info":"1.2kg/bag 12bags/ctn",
      "uom":"bag",
      "base_uom":"kg",
      "max_order_qty":2,
      "primary_unit":1.2,
      "secondary_unit":12,
      "big_uom":"ctn",
      "cbm":2.6,
      "gw":7.9,
      "qty":49,
      "added_date":"2020-09-12",
      "status":false,
      "weight":65
    },
    {
      "id":9412,
      "description":"Taro",
      "image":"https://source.unsplash.com/collection/1163637/480x480/?sig=36",
      "vendor_description":"奶香金萱(青茶)",
      "cost":30.3,
      "packing_info":"1.2kg/bag 12bags/ctn",
      "uom":"bag",
      "base_uom":"kg",
      "max_order_qty":2,
      "primary_unit":1.2,
      "secondary_unit":12,
      "big_uom":"ctn",
      "cbm":6.2,
      "gw":7.8,
      "qty":28,
      "added_date":"2020-09-12",
      "status":false,
      "weight":34
    },
    {
      "id":6231,
      "description":"Passion Fruit Syrup",
      "image":"https://source.unsplash.com/collection/1163637/480x480/?sig=23",
      "vendor_description":"寒天凍粉",
      "cost":20.6,
      "packing_info":"0.6kg/bag 24bags/ctn",
      "uom":"bag",
      "base_uom":"kg",
      "max_order_qty":0,
      "primary_unit":0.6,
      "secondary_unit":24,
      "big_uom":"ctn",
      "cbm":3.8,
      "gw":3.4,
      "qty":98,
      "added_date":"2020-09-12",
      "status":false,
      "weight":16
    },
    {
      "id":2438,
      "description":"Q Mochi - Original",
      "image":"https://source.unsplash.com/collection/1163637/480x480/?sig=81",
      "vendor_description":"奶精粉",
      "cost":130.7,
      "packing_info":"0.6kg/bag 24bags/ctn",
      "uom":"bag",
      "base_uom":"kg",
      "max_order_qty":4,
      "primary_unit":0.6,
      "secondary_unit":24,
      "big_uom":"ctn",
      "cbm":3.9,
      "gw":8.4,
      "qty":54,
      "added_date":"2020-09-12",
      "status":true,
      "weight":60
    },
    {
      "id":4921,
      "description":"Mung Bean Cake",
      "image":"https://source.unsplash.com/collection/1163637/480x480/?sig=64",
      "vendor_description":"雞蛋仔專用粉-原味",
      "cost":20.6,
      "packing_info":"600ml/bottle 20bottles/ctn",
      "uom":"bottle",
      "base_uom":"ml",
      "max_order_qty":5,
      "primary_unit":600,
      "secondary_unit":20,
      "big_uom":"ctn",
      "cbm":3.4,
      "gw":4.9,
      "qty":22,
      "added_date":"2020-09-12",
      "status":true,
      "weight":27
    },
    {
      "id":9060,
      "description":"Raw Soy Milk",
      "image":"https://source.unsplash.com/collection/1163637/480x480/?sig=97",
      "vendor_description":"奶蓋粉",
      "cost":120,
      "packing_info":"1.2kg/bag 12bags/ctn",
      "uom":"bag",
      "base_uom":"kg",
      "max_order_qty":9,
      "primary_unit":1.2,
      "secondary_unit":12,
      "big_uom":"ctn",
      "cbm":7.1,
      "gw":9,
      "qty":27,
      "added_date":"2020-09-12",
      "status":false,
      "weight":49
    },
    {
      "id":9777,
      "description":"Mini Taro balls",
      "image":"https://source.unsplash.com/collection/1163637/480x480/?sig=39",
      "vendor_description":"芋頭風味粉",
      "cost":10.5,
      "packing_info":"1.2kg/bag 12bags/ctn",
      "uom":"bag",
      "base_uom":"kg",
      "max_order_qty":5,
      "primary_unit":1.2,
      "secondary_unit":12,
      "big_uom":"ctn",
      "cbm":1.3,
      "gw":4.2,
      "qty":43,
      "added_date":"2020-09-12",
      "status":false,
      "weight":99
    },
    {
      "id":9229,
      "description":"Rice balls",
      "image":"https://source.unsplash.com/collection/1163637/480x480/?sig=13",
      "vendor_description":"奶蓋粉",
      "cost":130.7,
      "packing_info":"0.6kg/bag 24bags/ctn",
      "uom":"bag",
      "base_uom":"kg",
      "max_order_qty":3,
      "primary_unit":0.6,
      "secondary_unit":24,
      "big_uom":"ctn",
      "cbm":7,
      "gw":1,
      "qty":57,
      "added_date":"2020-09-12",
      "status":false,
      "weight":5
    },
    {
      "id":9442,
      "description":"Brown Sugar & Sesame Mochi",
      "image":"https://source.unsplash.com/collection/1163637/480x480/?sig=48",
      "vendor_description":"芋頭風味粉",
      "cost":20.6,
      "packing_info":"1.2kg/bag 12bags/ctn",
      "uom":"bag",
      "base_uom":"kg",
      "max_order_qty":6,
      "primary_unit":1.2,
      "secondary_unit":12,
      "big_uom":"ctn",
      "cbm":5.3,
      "gw":0.8,
      "qty":95,
      "added_date":"2020-09-12",
      "status":false,
      "weight":26
    },
    {
      "id":3139,
      "description":"Passion Fruit Syrup",
      "image":"https://source.unsplash.com/collection/1163637/480x480/?sig=42",
      "vendor_description":"蜜香紅茶",
      "cost":30.5,
      "packing_info":"0.6kg/bag 24bags/ctn",
      "uom":"bag",
      "base_uom":"kg",
      "max_order_qty":7,
      "primary_unit":0.6,
      "secondary_unit":24,
      "big_uom":"ctn",
      "cbm":1.4,
      "gw":2.5,
      "qty":8,
      "added_date":"2020-09-12",
      "status":true,
      "weight":62
    },
    {
      "id":1194,
      "description":"Taro balls",
      "image":"https://source.unsplash.com/collection/1163637/480x480/?sig=2",
      "vendor_description":"寒天凍粉",
      "cost":30.5,
      "packing_info":"1kg/bag 6bags/ctn",
      "uom":"bag",
      "base_uom":"kg",
      "max_order_qty":0,
      "primary_unit":1,
      "secondary_unit":6,
      "big_uom":"ctn",
      "cbm":5.1,
      "gw":9.1,
      "qty":84,
      "added_date":"2020-09-12",
      "status":false,
      "weight":32
    },
    {
      "id":1096,
      "description":"Sesame Rice Balls",
      "image":"https://source.unsplash.com/collection/1163637/480x480/?sig=56",
      "vendor_description":"焦糖布丁粉",
      "cost":10.5,
      "packing_info":"1kg/bag 6bags/ctn",
      "uom":"bag",
      "base_uom":"kg",
      "max_order_qty":6,
      "primary_unit":1,
      "secondary_unit":6,
      "big_uom":"ctn",
      "cbm":3.2,
      "gw":0.8,
      "qty":63,
      "added_date":"2020-09-12",
      "status":true,
      "weight":36
    },
    {
      "id":1426,
      "description":"Mung Bean Cake",
      "image":"https://source.unsplash.com/collection/1163637/480x480/?sig=58",
      "vendor_description":"寒天凍粉",
      "cost":10.5,
      "packing_info":"1kg/bag 6bags/ctn",
      "uom":"bag",
      "base_uom":"kg",
      "max_order_qty":0,
      "primary_unit":1,
      "secondary_unit":6,
      "big_uom":"ctn",
      "cbm":0.4,
      "gw":1.1,
      "qty":1,
      "added_date":"2020-09-12",
      "status":false,
      "weight":42
    },
    {
      "id":4285,
      "description":"Taro balls",
      "image":"https://source.unsplash.com/collection/1163637/480x480/?sig=71",
      "vendor_description":"黑糖粉",
      "cost":130.7,
      "packing_info":"0.6kg/bag 24bags/ctn",
      "uom":"bag",
      "base_uom":"kg",
      "max_order_qty":2,
      "primary_unit":0.6,
      "secondary_unit":24,
      "big_uom":"ctn",
      "cbm":4.6,
      "gw":4.5,
      "qty":80,
      "added_date":"2020-09-12",
      "status":false,
      "weight":62
    },
    {
      "id":8017,
      "description":"Taro balls",
      "image":"https://source.unsplash.com/collection/1163637/480x480/?sig=99",
      "vendor_description":"奶香金萱(青茶)",
      "cost":30.5,
      "packing_info":"1kg/bag 6bags/ctn",
      "uom":"bag",
      "base_uom":"kg",
      "max_order_qty":4,
      "primary_unit":1,
      "secondary_unit":6,
      "big_uom":"ctn",
      "cbm":1.1,
      "gw":9.6,
      "qty":66,
      "added_date":"2020-09-12",
      "status":false,
      "weight":43
    },
    {
      "id":1928,
      "description":"Taro",
      "image":"https://source.unsplash.com/collection/1163637/480x480/?sig=12",
      "vendor_description":"芋頭風味粉",
      "cost":10.5,
      "packing_info":"0.6kg/bag 24bags/ctn",
      "uom":"bag",
      "base_uom":"kg",
      "max_order_qty":6,
      "primary_unit":0.6,
      "secondary_unit":24,
      "big_uom":"ctn",
      "cbm":9.9,
      "gw":6.6,
      "qty":13,
      "added_date":"2020-09-12",
      "status":false,
      "weight":53
    },
    {
      "id":1648,
      "description":"Brown Sugar & Sesame Mochi",
      "image":"https://source.unsplash.com/collection/1163637/480x480/?sig=96",
      "vendor_description":"芋頭風味粉",
      "cost":40.2,
      "packing_info":"1.2kg/bag 12bags/ctn",
      "uom":"bag",
      "base_uom":"kg",
      "max_order_qty":1,
      "primary_unit":1.2,
      "secondary_unit":12,
      "big_uom":"ctn",
      "cbm":2,
      "gw":0.1,
      "qty":93,
      "added_date":"2020-09-12",
      "status":false,
      "weight":50
    },
    {
      "id":2170,
      "description":"Jelly Noodle",
      "image":"https://source.unsplash.com/collection/1163637/480x480/?sig=87",
      "vendor_description":"寒天凍粉",
      "cost":30.3,
      "packing_info":"600ml/bottle 20bottles/ctn",
      "uom":"bottle",
      "base_uom":"ml",
      "max_order_qty":4,
      "primary_unit":600,
      "secondary_unit":20,
      "big_uom":"ctn",
      "cbm":4.6,
      "gw":8.5,
      "qty":4,
      "added_date":"2020-09-12",
      "status":false,
      "weight":32
    },
    {
      "id":4487,
      "description":"Raw Soy Milk",
      "image":"https://source.unsplash.com/collection/1163637/480x480/?sig=30",
      "vendor_description":"寒天凍粉",
      "cost":30.3,
      "packing_info":"1.2kg/bag 12bags/ctn",
      "uom":"bag",
      "base_uom":"kg",
      "max_order_qty":8,
      "primary_unit":1.2,
      "secondary_unit":12,
      "big_uom":"ctn",
      "cbm":1.1,
      "gw":5.4,
      "qty":85,
      "added_date":"2020-09-12",
      "status":false,
      "weight":36
    },
    {
      "id":8823,
      "description":"Lemon Syrup",
      "image":"https://source.unsplash.com/collection/1163637/480x480/?sig=0",
      "vendor_description":"豆花粉",
      "cost":30.5,
      "packing_info":"1.2kg/bag 12bags/ctn",
      "uom":"bag",
      "base_uom":"kg",
      "max_order_qty":1,
      "primary_unit":1.2,
      "secondary_unit":12,
      "big_uom":"ctn",
      "cbm":0,
      "gw":9.4,
      "qty":3,
      "added_date":"2020-09-12",
      "status":false,
      "weight":17
    },
    {
      "id":4671,
      "description":"Taro",
      "image":"https://source.unsplash.com/collection/1163637/480x480/?sig=76",
      "vendor_description":"鮮芋仙‐燒仙草粉",
      "cost":20.6,
      "packing_info":"1kg/bag 6bags/ctn",
      "uom":"bag",
      "base_uom":"kg",
      "max_order_qty":0,
      "primary_unit":1,
      "secondary_unit":6,
      "big_uom":"ctn",
      "cbm":9.4,
      "gw":7.7,
      "qty":29,
      "added_date":"2020-09-12",
      "status":false,
      "weight":22
    },
    {
      "id":4646,
      "description":"Raw Soy Milk",
      "image":"https://source.unsplash.com/collection/1163637/480x480/?sig=94",
      "vendor_description":"奶蓋粉",
      "cost":130.7,
      "packing_info":"12pcs/box 18boxes/ctn",
      "uom":"box",
      "base_uom":"pcs",
      "max_order_qty":8,
      "primary_unit":12,
      "secondary_unit":18,
      "big_uom":"ctn",
      "cbm":6,
      "gw":3.5,
      "qty":84,
      "added_date":"2020-09-12",
      "status":true,
      "weight":97
    },
    {
      "id":9211,
      "description":"Raw Soy Milk",
      "image":"https://source.unsplash.com/collection/1163637/480x480/?sig=15",
      "vendor_description":"鮮芋仙紅茶",
      "cost":40.2,
      "packing_info":"600ml/bottle 20bottles/ctn",
      "uom":"bottle",
      "base_uom":"ml",
      "max_order_qty":4,
      "primary_unit":600,
      "secondary_unit":20,
      "big_uom":"ctn",
      "cbm":4.3,
      "gw":9.8,
      "qty":46,
      "added_date":"2020-09-12",
      "status":true,
      "weight":4
    },
    {
      "id":3015,
      "description":"Refined Sugar",
      "image":"https://source.unsplash.com/collection/1163637/480x480/?sig=22",
      "vendor_description":"雞蛋仔專用粉-原味",
      "cost":10.5,
      "packing_info":"1.2kg/bag 12bags/ctn",
      "uom":"bag",
      "base_uom":"kg",
      "max_order_qty":4,
      "primary_unit":1.2,
      "secondary_unit":12,
      "big_uom":"ctn",
      "cbm":6.3,
      "gw":4.2,
      "qty":54,
      "added_date":"2020-09-12",
      "status":true,
      "weight":95
    },
    {
      "id":3220,
      "description":"Brown Sugar & Peanut Mochi",
      "image":"https://source.unsplash.com/collection/1163637/480x480/?sig=77",
      "vendor_description":"寒天凍粉",
      "cost":30.5,
      "packing_info":"0.6kg/bag 24bags/ctn",
      "uom":"bag",
      "base_uom":"kg",
      "max_order_qty":0,
      "primary_unit":0.6,
      "secondary_unit":24,
      "big_uom":"ctn",
      "cbm":6.5,
      "gw":1.8,
      "qty":12,
      "added_date":"2020-09-12",
      "status":false,
      "weight":69
    },
    {
      "id":7351,
      "description":"Sesame Rice Balls",
      "image":"https://source.unsplash.com/collection/1163637/480x480/?sig=50",
      "vendor_description":"奶蓋粉",
      "cost":30.5,
      "packing_info":"0.6kg/bag 24bags/ctn",
      "uom":"bag",
      "base_uom":"kg",
      "max_order_qty":8,
      "primary_unit":0.6,
      "secondary_unit":24,
      "big_uom":"ctn",
      "cbm":9.5,
      "gw":3.1,
      "qty":69,
      "added_date":"2020-09-12",
      "status":true,
      "weight":60
    },
    {
      "id":6795,
      "description":"Q Mochi - Brown Sugar ",
      "image":"https://source.unsplash.com/collection/1163637/480x480/?sig=64",
      "vendor_description":"奶香金萱(青茶)",
      "cost":130.7,
      "packing_info":"600ml/bottle 20bottles/ctn",
      "uom":"bottle",
      "base_uom":"ml",
      "max_order_qty":9,
      "primary_unit":600,
      "secondary_unit":20,
      "big_uom":"ctn",
      "cbm":1.9,
      "gw":5.6,
      "qty":22,
      "added_date":"2020-09-12",
      "status":false,
      "weight":30
    },
    {
      "id":8781,
      "description":"Sesame Rice Balls",
      "image":"https://source.unsplash.com/collection/1163637/480x480/?sig=17",
      "vendor_description":"寒天凍粉",
      "cost":20.6,
      "packing_info":"1.2kg/bag 12bags/ctn",
      "uom":"bag",
      "base_uom":"kg",
      "max_order_qty":5,
      "primary_unit":1.2,
      "secondary_unit":12,
      "big_uom":"ctn",
      "cbm":6.2,
      "gw":0.1,
      "qty":14,
      "added_date":"2020-09-12",
      "status":false,
      "weight":31
    },
    {
      "id":6956,
      "description":"Brown Sugar & Sesame Mochi",
      "image":"https://source.unsplash.com/collection/1163637/480x480/?sig=90",
      "vendor_description":"雞蛋仔專用粉-原味",
      "cost":30.3,
      "packing_info":"1.2kg/bag 12bags/ctn",
      "uom":"bag",
      "base_uom":"kg",
      "max_order_qty":9,
      "primary_unit":1.2,
      "secondary_unit":12,
      "big_uom":"ctn",
      "cbm":7.7,
      "gw":6.1,
      "qty":17,
      "added_date":"2020-09-12",
      "status":true,
      "weight":69
    },
    {
      "id":7565,
      "description":"Lemon Syrup",
      "image":"https://source.unsplash.com/collection/1163637/480x480/?sig=98",
      "vendor_description":"寒天凍粉",
      "cost":30.5,
      "packing_info":"1kg/bag 6bags/ctn",
      "uom":"bag",
      "base_uom":"kg",
      "max_order_qty":6,
      "primary_unit":1,
      "secondary_unit":6,
      "big_uom":"ctn",
      "cbm":1,
      "gw":7.6,
      "qty":42,
      "added_date":"2020-09-12",
      "status":false,
      "weight":40
    },
    {
      "id":5031,
      "description":"Brown Sugar & Peanut Mochi",
      "image":"https://source.unsplash.com/collection/1163637/480x480/?sig=55",
      "vendor_description":"焦糖粉",
      "cost":40.2,
      "packing_info":"1.2kg/bag 12bags/ctn",
      "uom":"bag",
      "base_uom":"kg",
      "max_order_qty":6,
      "primary_unit":1.2,
      "secondary_unit":12,
      "big_uom":"ctn",
      "cbm":4.3,
      "gw":0.2,
      "qty":93,
      "added_date":"2020-09-12",
      "status":false,
      "weight":14
    }
  ]
  constructor() { }
}
